version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: inventory_app
      SERVICE_TAGS: dev
    working_dir: /var/www/inventory-system
    volumes:
      - ./:/var/www/inventory-system
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - webserver

  #Nginx Service
  webserver:
    image: nginx:1.17.3
    container_name: inventory_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/inventory-system
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:5.7.27
    container_name: inventory_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - $PWD/docker/mysql:/var/lib/mysql

  #PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    container_name: inventory_phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    links:
      - db:db